degre6: degre6.o f2c.o c2f.o menu2.o table.o
	c++ -o degre6 degre6.o f2c.o c2f.o menu2.o table.o
degre6.o: degre6.cpp
	c++ -c degre6.cpp
f2c.o: f2c.cpp
	c++ -c f2c.cpp
c2f.o: c2f.cpp
	c++ -c c2f.cpp
menu2.o: menu2.cpp
	c++ -c menu2.cpp
table.o: table.cpp
	c++ -c table.cpp
